baseurl = "https://benbailey.me/"
languageCode = "en-us"
title = "benfb"
theme = "hyde"
pygmentsstyle = "autumn"
publishdir = "www"

[permalinks]
    post = "/:year/:month/:filename/"
    code = "/:filename/"

[params]
    themeColor = "theme-base-08"
    home = "Home"
    highlight = "sunburst"
    rss = true
    description = "Student and devops in Amherst and Austin."
    email = "mailto:bennettbailey@gmail.com"
    twitter = "https://twitter.com/bennett"
    github = "https://github.com/benfb"
