baseurl = "https://benbailey.me/"
languageCode = "en-us"
title = "Ben Bailey"
theme = "etch"

[params]
  description = "DevOps in Austin at Pingboard. Occasionally baseball at [25th Man](https://25thman.com)."
  highlight = true
  dark = "auto"
  dateFormatToUse = "2006-01-02"

pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true

[author]
  name = "Ben Bailey"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "https://about.benbailey.me"
    weight = 20

[markup]
  [markup.tableOfContents]
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe = true
