baseurl = "https://benbailey.me/"
languageCode = "en-us"
title = "Ben Bailey"
theme = "etch"

[params]
mastodonUrl = "https://mastodon.social/@benfb"
tinylyticsSiteID = "Nskj6_ssFxxLkBzyxnpi"

pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true

[permalinks]
posts = '/:title/'

[params.author]
name = "Ben Bailey"

[menu]
[[menu.main]]
identifier = "posts"
name = "posts"
title = "posts"
url = "/"
weight = 10

[[menu.main]]
identifier = "about"
name = "about"
title = "about"
url = "/about"
weight = 20

[[menu.main]]
identifier = "rss"
name = "rss"
title = "rss"
url = "/index.xml"
weight = 30

[markup.goldmark.renderer]
# Allows HTML in Markdown
unsafe = true
